inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

AllCops:
  Exclude:
    # the cache path in .gitlab-ci.yml is vendor/ruby
    # and it uses a gemfile in gemfiles/, so it is relative
    - "gemfiles/vendor/ruby/**/*"

# Metrics cops are disabled in Standard by default
Metrics:
  Enabled: true

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Enabled: false