inherit_mode:
  merge:
    - Exclude

inherit_gem:
  rubocop-lts: rubocop-lts.yml

AllCops:
  Exclude:
    - "test/sigstore-conformance/**/*"
    - "test/tuf-conformance/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "gemfiles/vendor/bundle/**/*"

# Metrics cops are disabled in Standard by default
Metrics:
  Enabled: true

Layout/LineLength:
  Max: 120

RSpec/NestedGroups:
  Enabled: false